/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddMenuModal: typeof import('./components/restaurant/AddMenuModal.vue')['default']
    BaseModal: typeof import('./components/atom/BaseModal.vue')['default']
    DropdownMenu: typeof import('./components/DropdownMenu.vue')['default']
    ErrorText: typeof import('./components/atom/ErrorText.vue')['default']
    Field: typeof import('./components/Field.vue')['default']
    HelperMessage: typeof import('./components/atom/HelperMessage.vue')['default']
    Input: typeof import('./components/atom/Input.vue')['default']
    Label: typeof import('./components/atom/Label.vue')['default']
    MenuItem: typeof import('./components/restaurant/MenuItem.vue')['default']
    MenusTab: typeof import('./components/restaurant/MenusTab.vue')['default']
    Multiselect: typeof import('./components/Multiselect.vue')['default']
    OrderCard: typeof import('./components/restaurant/OrderCard.vue')['default']
    OrderDetails: typeof import('./components/restaurant/OrderDetails.vue')['default']
    OrderItem: typeof import('./components/restaurant/OrderItem.vue')['default']
    OrderLists: typeof import('./components/restaurant/OrderLists.vue')['default']
    OrderSummary: typeof import('./components/restaurant/OrderSummary.vue')['default']
    ProfileInformation: typeof import('./components/restaurant/ProfileInformation.vue')['default']
    ProfileMenu: typeof import('./components/restaurant/ProfileMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('./components/atom/Textarea.vue')['default']
    TheAvatar: typeof import('./components/atom/TheAvatar.vue')['default']
    TheButton: typeof import('./components/atom/TheButton.vue')['default']
    TheCard: typeof import('./components/atom/TheCard.vue')['default']
    TheHeader: typeof import('./components/restaurant/TheHeader.vue')['default']
    TheLink: typeof import('./components/atom/TheLink.vue')['default']
    TheSelect: typeof import('./components/atom/TheSelect.vue')['default']
    UpdateOrderModal: typeof import('./components/restaurant/UpdateOrderModal.vue')['default']
  }
}
